import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Card from '@/components/Card'

export default function Home() {
  return (
    <>
      <Head>
        <title>Fether Note</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-900">
        <div className="container mx-auto h-screen px-6 relative">
          <Navbar />

          <div className="pt-32">
            <Card />
          </div>
        </div>
      </main>
    </>
  )
}
